### ISSUE TITLE
NewWithAddr only works if client has access to '/'

### ISSUE THREAD

**Issue by borud** [telenordigital/lassie-go#1]
This only works if Congress API Token permissions are set to full access.  If a more restrictive access is set for the API token, this fails.  Not sure if this should be a Congress change or lassie change.

```
func NewWithAddr(addr, token string) (*Client, error) {
	c := &Client{
		addr:  addr,
		token: token,
	}
	return c, c.ping()
}

func (c *Client) ping() error {
	return c.get("/", nil)
}
```

**Comment by gordonklaus** [comment]
What do you think, @stalehd?  Can congress accept GETs to "/" with more restricted API tokens (restricted to a single application)?  Is there another way for us to ping?
